import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { randomBytes } from 'crypto';
import { PRISMA } from '../../common/prisma.module';
import type { PrismaClient } from '@campusgo/database';
import { assertOwnJob, jobVisibleToCollege, type Viewer } from '../jobs/job-scope.util';
import { SubmitEmployerFeedbackDto } from './dto';

@Injectable()
export class EmployerFeedbackService {
  constructor(@Inject(PRISMA) private readonly prisma: PrismaClient) {}

  private async uniqueToken(): Promise<string> {
    for (let i = 0; i < 5; i++) {
      const token = randomBytes(9).toString('base64url');
      const clash = await this.prisma.employerFeedback.findUnique({ where: { publicToken: token } });
      if (!clash) return token;
    }
    throw new BadRequestException('Could not allocate a feedback link, please retry');
  }

  // ─────────────── Officer / Admin ───────────────

  // Idempotent: returns the existing link if one was already generated for
  // this job, rather than minting a second (which would orphan the first).
  // Restricted to the college's OWN jobs — a PLATFORM-broadcast job's
  // feedback link is the Platform Admin's to generate (see
  // getOrCreateLinkForPlatformJob), since they're the ones with the
  // relationship with that employer, not any one targeted college.
  async getOrCreateLink(collegeId: string, jobId: string, viewer?: Viewer) {
    const job = await this.prisma.job.findFirst({ where: { id: jobId, collegeId, scope: 'COLLEGE' } });
    if (!job) throw new NotFoundException('Job not found');
    assertOwnJob(job, viewer);

    const existing = await this.prisma.employerFeedback.findUnique({ where: { jobId } });
    if (existing) return this.toOfficerShape(existing);

    const created = await this.prisma.employerFeedback.create({
      data: { collegeId, jobId, publicToken: await this.uniqueToken() },
    });
    return this.toOfficerShape(created);
  }

  async getForJob(collegeId: string, jobId: string, viewer?: Viewer) {
    const job = await this.prisma.job.findFirst({
      where: { id: jobId, ...jobVisibleToCollege(collegeId) },
    });
    if (!job) throw new NotFoundException('Job not found');
    assertOwnJob(job, viewer);

    const feedback = await this.prisma.employerFeedback.findUnique({ where: { jobId } });
    return feedback ? this.toOfficerShape(feedback) : null;
  }

  // Every link generated by this college, submitted or not — the placement
  // team's overview of who's responded. Platform-job feedback (collegeId
  // null) is excluded — that belongs to the Platform Admin's own summary.
  async listForCollege(collegeId: string) {
    const rows = await this.prisma.employerFeedback.findMany({
      where: { collegeId },
      include: { job: { select: { title: true, companyName: true, company: { select: { name: true } } } } },
      orderBy: { createdAt: 'desc' },
    });
    return rows.map((f) => ({
      jobId: f.jobId,
      jobTitle: f.job.title,
      companyName: f.job.company?.name ?? f.job.companyName ?? 'Company',
      ...this.toOfficerShape(f),
    }));
  }

  private toOfficerShape(f: {
    id: string;
    publicToken: string;
    contactPerson: string | null;
    designation: string | null;
    knowledgeSkills: number | null;
    communicationSkills: number | null;
    problemSolving: number | null;
    teamworkAdaptability: number | null;
    professionalism: number | null;
    overallEmployability: number | null;
    curriculumRelevance: number | null;
    trainingEffectiveness: number | null;
    improvementAreas: string | null;
    suggestions: string | null;
    recruitAgain: string | null;
    submittedAt: Date | null;
  }) {
    return {
      id: f.id,
      publicToken: f.publicToken,
      submitted: f.submittedAt != null,
      submittedAt: f.submittedAt,
      contactPerson: f.contactPerson,
      designation: f.designation,
      ratings: f.submittedAt
        ? {
            knowledgeSkills: f.knowledgeSkills,
            communicationSkills: f.communicationSkills,
            problemSolving: f.problemSolving,
            teamworkAdaptability: f.teamworkAdaptability,
            professionalism: f.professionalism,
            overallEmployability: f.overallEmployability,
            curriculumRelevance: f.curriculumRelevance,
            trainingEffectiveness: f.trainingEffectiveness,
          }
        : null,
      improvementAreas: f.improvementAreas,
      suggestions: f.suggestions,
      recruitAgain: f.recruitAgain,
    };
  }

  // ─────────────── Platform Admin ───────────────
  // A platform-broadcast job is one shared hiring process across every
  // targeted college, so it gets the same single Job-scoped feedback record —
  // the platform admin can generate/view it directly (no collegeId to scope
  // by), same as any college that job was broadcast to.

  async getOrCreateLinkForPlatformJob(jobId: string) {
    const job = await this.prisma.job.findFirst({ where: { id: jobId, scope: 'PLATFORM' } });
    if (!job) throw new NotFoundException('Job not found');

    const existing = await this.prisma.employerFeedback.findUnique({ where: { jobId } });
    if (existing) return this.toOfficerShape(existing);

    const created = await this.prisma.employerFeedback.create({
      data: { collegeId: null, jobId, publicToken: await this.uniqueToken() },
    });
    return this.toOfficerShape(created);
  }

  async getForPlatformJob(jobId: string) {
    const job = await this.prisma.job.findFirst({ where: { id: jobId, scope: 'PLATFORM' } });
    if (!job) throw new NotFoundException('Job not found');

    const feedback = await this.prisma.employerFeedback.findUnique({ where: { jobId } });
    return feedback ? this.toOfficerShape(feedback) : null;
  }

  // ─────────────── Public (no auth) ───────────────

  async getPublicContext(token: string) {
    const feedback = await this.prisma.employerFeedback.findUnique({
      where: { publicToken: token },
      include: {
        job: {
          select: {
            title: true,
            companyName: true,
            eligibleProgrammes: true,
            graduationYears: true,
            company: { select: { name: true, industry: true } },
          },
        },
      },
    });
    if (!feedback) throw new NotFoundException('This feedback link is invalid');

    return {
      submitted: feedback.submittedAt != null,
      jobTitle: feedback.job.title,
      companyName: feedback.job.company?.name ?? feedback.job.companyName ?? 'the company',
      industry: feedback.job.company?.industry ?? null,
      programmes: feedback.job.eligibleProgrammes,
      academicYears: feedback.job.graduationYears,
    };
  }

  async submitPublic(token: string, dto: SubmitEmployerFeedbackDto) {
    const feedback = await this.prisma.employerFeedback.findUnique({ where: { publicToken: token } });
    if (!feedback) throw new NotFoundException('This feedback link is invalid');
    if (feedback.submittedAt) {
      throw new BadRequestException('Feedback has already been submitted for this link');
    }

    await this.prisma.employerFeedback.update({
      where: { publicToken: token },
      data: {
        contactPerson: dto.contactPerson.trim(),
        designation: dto.designation?.trim() || null,
        knowledgeSkills: dto.knowledgeSkills,
        communicationSkills: dto.communicationSkills,
        problemSolving: dto.problemSolving,
        teamworkAdaptability: dto.teamworkAdaptability,
        professionalism: dto.professionalism,
        overallEmployability: dto.overallEmployability,
        curriculumRelevance: dto.curriculumRelevance,
        trainingEffectiveness: dto.trainingEffectiveness,
        improvementAreas: dto.improvementAreas?.trim() || null,
        suggestions: dto.suggestions?.trim() || null,
        recruitAgain: dto.recruitAgain,
        submittedAt: new Date(),
      },
    });
    return { success: true };
  }
}
