import { BadRequestException, Body, Controller, Get, Param, Post } from '@nestjs/common';
import { UserRole } from '@campusgo/shared';
import type { JwtPayload } from '@campusgo/shared';
import { CurrentUser, Public, Roles } from '../../common/decorators';
import { EmployerFeedbackService } from './employer-feedback.service';
import { SubmitEmployerFeedbackDto } from './dto';

/** Officer/admin: generate and view the employer feedback link for one of their own jobs. */
@Controller('jobs')
@Roles(UserRole.COLLEGE_ADMIN, UserRole.PLACEMENT_OFFICER)
export class EmployerFeedbackController {
  constructor(private readonly feedback: EmployerFeedbackService) {}

  private collegeId(user: JwtPayload): string {
    if (!user.collegeId) throw new BadRequestException('No college context');
    return user.collegeId;
  }

  @Post(':id/feedback-link')
  async getOrCreateLink(@CurrentUser() user: JwtPayload, @Param('id') id: string) {
    return {
      data: await this.feedback.getOrCreateLink(this.collegeId(user), id, {
        role: user.role,
        userId: user.sub,
      }),
    };
  }

  @Get(':id/feedback')
  @Roles(UserRole.COLLEGE_ADMIN, UserRole.PLACEMENT_OFFICER, UserRole.PLACEMENT_COORDINATOR)
  async getForJob(@CurrentUser() user: JwtPayload, @Param('id') id: string) {
    return {
      data: await this.feedback.getForJob(this.collegeId(user), id, {
        role: user.role,
        userId: user.sub,
      }),
    };
  }
}

/** Officer/admin: every employer feedback link generated by this college. */
@Controller('feedback/employers')
@Roles(UserRole.COLLEGE_ADMIN, UserRole.PLACEMENT_OFFICER)
export class OfficerEmployerFeedbackListController {
  constructor(private readonly feedback: EmployerFeedbackService) {}

  private collegeId(user: JwtPayload): string {
    if (!user.collegeId) throw new BadRequestException('No college context');
    return user.collegeId;
  }

  @Get()
  @Roles(UserRole.COLLEGE_ADMIN, UserRole.PLACEMENT_OFFICER, UserRole.PLACEMENT_COORDINATOR)
  async list(@CurrentUser() user: JwtPayload) {
    return { data: await this.feedback.listForCollege(this.collegeId(user)) };
  }
}

/** Platform Admin: same, for their own broadcast jobs. */
@Controller('platform/jobs')
@Roles(UserRole.PLATFORM_ADMIN)
export class PlatformEmployerFeedbackController {
  constructor(private readonly feedback: EmployerFeedbackService) {}

  @Post(':id/feedback-link')
  async getOrCreateLink(@Param('id') id: string) {
    return { data: await this.feedback.getOrCreateLinkForPlatformJob(id) };
  }

  @Get(':id/feedback')
  async getForJob(@Param('id') id: string) {
    return { data: await this.feedback.getForPlatformJob(id) };
  }
}

/** Public (no auth): the employer's own feedback submission page. */
@Controller('public/employer-feedback')
export class PublicEmployerFeedbackController {
  constructor(private readonly feedback: EmployerFeedbackService) {}

  @Public()
  @Get(':token')
  async context(@Param('token') token: string) {
    return { data: await this.feedback.getPublicContext(token) };
  }

  @Public()
  @Post(':token')
  async submit(@Param('token') token: string, @Body() dto: SubmitEmployerFeedbackDto) {
    return { data: await this.feedback.submitPublic(token, dto) };
  }
}
